solar_auction/administration/urls.py
from django.urls import path
from . import views

app_name = 'administration'

urlpatterns = [
    path('', views.index, name='admin_index'),
    path('approved_users',
         views.ApprovedUsersView.as_view(), name='approved_users'),
    path('users_waiting', views.UnApprovedUsersView.as_view(), name='users_waiting'),
    path('documents_awaited', views.DocumentsUploadedView.as_view(),
         name='undocumented_users'),
    path('email_unverified', views.EmailUnverifiedView.as_view(),
         name='unverified_users'),
    path('approved_catalogue', views.ApprovedCatalogueView.as_view(),
         name='approved_catalogue'),
    path('catalogue_waiting', views.UnApprovedCatalogueView.as_view(),
         name='catalogue_waiting'),
    path('user_detail/<pk>',
         views.UserProfileView.as_view(), name='user_detail'),
    path('catalogue_detail/<slug>',
         views.AdminCatalogueView.as_view(), name='catalogue_detail'),
    path('catalogue_action/<slug>',
         views.catalogue_action, name='catalogue_action'),
    path('user_action/<pk>',
         views.user_action, name='user_action'),
    path('finished_auctions', views.AuctionOverView.as_view(),
         name='finished_auctions'),
    path('orders_list', views.OrdersView.as_view(),
         name='user_orders'),
    #     path('logs', views.LogsView.as_view(),
    #          name='audit_logs'),

]

solar_auction/marketplace/urls.py
from django.urls import path
from . import views

app_name = 'marketplace'

urlpatterns = [
    path('', views.CatalogueListView.as_view(), name='all_catalogue'),
    path('marketplace_history', views.AuctionOverView.as_view(),
         name='history_catalogue'),
    path('detail/<slug:slug>/', views.CatalogueDetailView.as_view(),
         name='catalogue_detail'),
    path('user/catalogues/', views.UserCatalogueView.as_view(),
         name='user_catalogue'),
     path('bid_detail/<pk>/', views.BidDetailView.as_view(),
         name='bid_detail'),
    path('user/bids/', views.UserBidView.as_view(), name='user_bids'),
    path('user/add_item', views.addItemView, name='add_item'),
    path('<slug>/add_bid/', views.addBidView, name='add_bid'),
    path('notify/<slug>', views.notify_winner, name='notify_winner'),
    path('search', views.SearchView.as_view(), name='search')
]

solar_auction/payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    path('<slug>', views.home, name='payments_home'),
    path("payment/<slug>", views.order_payment, name="payment"),
    path('callback/', views.callback, name='payment_callback'),
    path('user_orders/', views.UserOrderView.as_view(), name='user_orders'),
]

solar_auction/solar_auction/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.i18n import JavaScriptCatalog
from django.contrib.auth import views as auth_views
from registration import views as registration_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jsi18n', JavaScriptCatalog.as_view(), name='js_catalog'),
    path('logout', registration_views.user_logout, name='logout'),
    path('', include('registration.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('dashboards/', include('administration.urls')),
    path('password-reset/', registration_views.ResetPasswordView.as_view(),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('payments/', include('payments.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

solar_auction/administration/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render
from django.contrib.auth.models import User
from razorpay import Order
from registration.models import UserProfileInfo, Documents
from marketplace.models import Catalogue, CatalogueFile
from django.http import Http404, HttpResponseRedirect
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy
from solar_auction.settings import EMAIL_HOST_USER
from django.core.mail import send_mail
from django.utils import timezone
from auditlog.models import LogEntry
from django.views.decorators.clickjacking import xframe_options_exempt
from payments.models import Order
from payments.constants import PaymentStatus


@staff_member_required
def index(request):
    return render(request, 'administration/index.html')


@method_decorator(staff_member_required, name='dispatch')
class ApprovedUsersView(ListView):
    model = UserProfileInfo
    template_name = 'administration/users.html'
    context_object_name = 'UserInfos'

    def get_queryset(self):
        try:
            return UserProfileInfo.objects.filter(admin_approved=True)
        except:
            raise Http404()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Approved Users'
        return context


@method_decorator(staff_member_required, name='dispatch')
@method_decorator(xframe_options_exempt, name='dispatch')
class UnApprovedUsersView(ListView):
    model = UserProfileInfo
    template_name = 'administration/users.html'
    context_object_name = 'UserInfos'

    def get_queryset(self):
        try:
            return UserProfileInfo.objects.filter(admin_approved=False, documents_uploaded=True)
        except:
            raise Http404()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Users waiting approval'

        return context


@method_decorator(staff_member_required, name='dispatch')
class ApprovedCatalogueView(ListView):
    model = Catalogue
    template_name = 'administration/catalogue.html'
    context_object_name = 'CatalogueInfos'

    def get_queryset(self):
        try:
            return Catalogue.objects.filter(admin_approved=True, end_date__gt=timezone.now())
        except:
            raise Http404()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Approved Catalogue'

        return context


@method_decorator(staff_member_required, name='dispatch')
class UnApprovedCatalogueView(ListView):
    model = Catalogue
    template_name = 'administration/catalogue.html'
    context_object_name = 'CatalogueInfos'

    def get_queryset(self):
        try:
            return Catalogue.objects.filter(admin_approved=False, end_date__gt=timezone.now())
        except:
            raise Http404()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Catalogue waiting approval'
        return context


@method_decorator(staff_member_required, name='dispatch')
class UserProfileView(DetailView):
    model = UserProfileInfo
    template_name = 'administration/user_detail.html'
    context_object_name = 'userinfo'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:

            user_documents = Documents.objects.get(user=kwargs['object'].user)

            context['user_file_present'] = True
            context['user_files'] = user_documents
        except:
            context['user_file_present'] = False

        return context


@method_decorator(staff_member_required, name='dispatch')
class AdminCatalogueView(DetailView):
    model = Catalogue
    template_name = 'administration/catalogue_detail.html'
    context_object_name = 'catalogue'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            catalogue_file = CatalogueFile.objects.get(
                catalogue_name=context['catalogue'])
            context['file_present'] = True
            context['catalogue_file'] = catalogue_file
        except:
            context['file_present'] = False
        return context


@method_decorator(staff_member_required, name='dispatch')
class AuctionOverView(ListView):
    model = Catalogue
    template_name = 'administration/catalogue.html'
    context_object_name = 'CatalogueInfos'

    def get_queryset(self):

        try:
            return Catalogue.objects.filter(end_date__lt=timezone.now())
        except:
            raise Http404()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Finished Auctions'

        return context


@method_decorator(staff_member_required, name='dispatch')
class DocumentsUploadedView(ListView):
    model = UserProfileInfo
    template_name = 'administration/users.html'
    context_object_name = 'UserInfos'

    def get_queryset(self):
        try:
            user_list = User.objects.filter(is_active=True)
            profile_list = []
            for user in user_list:
                user_profile = UserProfileInfo.objects.get(user=user)
                if not user_profile.documents_uploaded:
                    profile_list.append(user_profile)

            return profile_list
        except:
            raise Http404()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Awaiting documents'
        return context


@method_decorator(staff_member_required, name='dispatch')
class EmailUnverifiedView(ListView):
    model = UserProfileInfo
    template_name = 'administration/users.html'
    context_object_name = 'UserInfos'

    def get_queryset(self):
        try:

            user_list = User.objects.filter(is_active=False)

            profile_list = []
            for user in user_list:
                profile_list.append(UserProfileInfo.objects.get(user=user))

            return profile_list
        except:
            raise Http404()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Awaiting verification'
        return context


@staff_member_required
def user_action(request, pk):
    current_user = UserProfileInfo.objects.get(pk=pk)
    current_user_email = User.objects.get(pk=pk).email
    if 'approve' in request.POST:
        current_user.admin_approved = True
        subject = "Membership Approved"
        message = "You have been approved to participate on our website."
        current_user.save()
    elif 'remove' in request.POST:
        current_user.admin_approved = False
        subject = "Membership Suspended"
        message = "You have been suspended from participating on our website."
        current_user.save()
    elif 'reject' in request.POST:
        user_documents = Documents.objects.get(user=User.objects.get(pk=pk))
        current_user.documents_uploaded = False
        user_documents.delete()
        subject = "Documents rejected"
        message = "Your uploaded documents were rejected by an administrator due to a discrepancy."
        current_user.save()
    elif 'notify' in request.POST:
        subject = "Documents requested"
        message = "You need to upload relevant documents on our website to participate further."
    elif 'delete' in request.POST:
        subject = "Membership Banned"
        message = "You have been permanently suspended from participating on our website."
        current_user.delete()
    send_mail(subject,
              message, EMAIL_HOST_USER, [current_user_email], fail_silently=False)
    return HttpResponseRedirect(reverse('administration:admin_index'))


@staff_member_required
def catalogue_action(request, slug):
    catalogue = Catalogue.objects.get(slug=slug)
    catalogue_owner = UserProfileInfo.objects.get(
        pk=catalogue.owner.id)
    catalogue_owner_email = User.objects.get(pk=catalogue_owner.id).email
    if 'token_amount' in request.POST:
        if request.POST['token_amount']:
            catalogue.broker_fees = request.POST['token_amount']
            catalogue.save()
    if 'approve' in request.POST:
        catalogue.admin_approved = True
        subject = "Catalogue Approved"
        message = " Your catalogue " + \
            str(catalogue.name)+" is approved for auction."
        catalogue.save()
    elif 'remove' in request.POST:
        catalogue.admin_approved = False
        subject = "Catalogue Pulled"
        message = " Your catalogue " + \
            str(catalogue.name)+" has been pulled from auction."
        catalogue.save()
    elif 'delete' in request.POST:
        subject = "Catalogue"
        message = "The item you posted " + \
            str(catalogue.name) + " has been removed from the marketplace."
        catalogue.delete()
    send_mail(subject,
              message, EMAIL_HOST_USER, [catalogue_owner_email], fail_silently=False)
    return HttpResponseRedirect(reverse('administration:admin_index'))


# class LogsView(ListView):
#     model = LogEntry
#     template_name = 'administration/audit_log.html'
#     context_object_name = 'logs'

@method_decorator(staff_member_required, name='dispatch')
class OrdersView(ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'administration/order_list.html'

    def get_queryset(self):
        return Order.objects.filter(payment_status=PaymentStatus.SUCCESS)

solar_auction/administration/templates/administration/catalogue.html
{% extends 'registration/base.html' %}
{% load static %}
{% block title %}
   {{page_title}}
{% endblock %}

{% block content %} 
    <div class="admin-content"> 
        {% if CatalogueInfos %}
                    <table class="table table-hover table-striped" id="sortable">
                        <thead>
                            <tr>
                                
                                <th scope="col" onclick="sortTable(0)">Name</th>
                                <th scope="col" onclick="sortTable(1)">Owner</th>
                                <th scope="col" onclick="sortTable(2)">Minimum Bid Amount</th>
                                <th scope="col" onclick="sortTable(3)">End date</th>
                                <th scope="col" onclick="sortTable(4)">Auction Status</th>
                        
                            </tr>
                        </thead>
                        <tbody>
                         {% for catalogue_info in CatalogueInfos %}
                            <tr>
                                
                                <td><a href="{% url 'administration:catalogue_detail' catalogue_info.slug %}">{{catalogue_info}}</a></td>
                                <td>{{catalogue_info.owner.username}}</td>
                                <td>{{catalogue_info.starting_bid}}</td>
                            
                                <td>{{catalogue_info.end_date}}</td>
                                <td>{% if catalogue_info.auction_status %}On Auction{% else %}Auction Over{% endif %}</td>
                                
                            </tr> 
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
    </div>
 {% endblock %}

solar_auction/administration/templates/administration/catalogue_detail.html
{% extends 'registration/base.html' %}
{% load static %}
{% block title %}
   Catalogue Detail
{% endblock %}

{% block content %} 
    <div class="admin-content"> 
                <p>Catalogue Name: {{catalogue.name}}</p>
                <p>Detail: {{catalogue.details}}</p>
                <p>Posted by: {{catalogue.owner}}</p>
                <p>Ends on: {{catalogue.end_date}}</p>
                <p>Starting bid: {{catalogue.starting_bid}}</p>
                <p>Bidding strategy: {% if catalogue.strategy == 'ascending' %}Low to High{% elif catalogue.strategy == 'descending' %}High to Low{% else %}Get Quotations{% endif %}</p>
                <p>Admin Approved: {{catalogue.admin_approved}}</p>    
                <p>Broker fee: {% if catalogue.broker_fees %}{{catalogue.broker_fees}}{% else %}Nil{% endif %}</p>
                {% if file_present %}
                    <button id="button" onclick="showhide()">Additional customer requirements</button>
                    <br>
                    <br>
                    <div class="container" id="toggalable" style="display:none;">
                        <embed src="{{catalogue_file.file_name.url}}" width="1000" height="375" type="application/pdf">
                    </div>
                {% endif %}
                    
                <br>
                <br>
                
                <form style="display: inline;" action="{% url 'administration:catalogue_action' slug=catalogue.slug%}" method=POST>
                        {% csrf_token %}
                        {% if catalogue.admin_approved %}
                            <button id="approve-btn" name="remove" type="submit">Withdraw Approval</button>
                        {% else %}
                        
                            <input type="number" name="token_amount"  placeholder="Brokerage" />
                            <button id="approve-btn" name="approve" type="submit" >Approve</button>
                            <button id="approve-btn" name="delete" type="submit">Delete Catalogue</button>
                            
                        {% endif %}
                </form>
    </div>
    
 {% endblock %}

solar_auction/administration/templates/administration/index.html
{% extends 'registration/base.html' %}
{% load static %}
{% block title %}
    Admin Dashboards
{% endblock %}

{% block content %}   

  


{% endblock %}

solar_auction/administration/templates/administration/order_list.html
{% extends 'registration/base.html' %}
{% block title %}
    All orders
{% endblock %}
{% block content %}
    {% if orders %}
        <table class="table table-hover table-striped" id="sortable">
            <thead>
                <tr>
                    <th scope="col" onclick="sortTable(0)">Catalogue Name</th>
                    <th scope="col" onclick="sortTable(1)">User</th>
                    <th scope="col" onclick="sortTable(2)">Amount</th>
                    
                    <th scope="col" onclick="sortTable(3)">Order Id</th>
                    <th scope="col" onclick="sortTable(4)">Payment Id</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                    <tr>
                        <td><a href="{% url 'marketplace:catalogue_detail' order.catalogue.slug %}">{{order.catalogue}}</a></td>
                        <td>{{order.owner}}</td>
                        <td>{{order.fee_amount}}</td>
                        
                        <td>{{order.order_id}}</td>
                        <td>{{order.payment_id}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

solar_auction/administration/templates/administration/user_detail.html
{% extends 'registration/base.html' %}
{% load static %}
{% block title %}
   User details
{% endblock %}

{% block content %} 
    <div class="admin-content"> 
                <p>Username: {{userinfo.user.username}}</p>
                <p>Contact Person: {{userinfo.contact_person}}</p>
                <p>Phone: {{userinfo.phone}}</p>
                <p>Admin Approved: {{userinfo.admin_approved}}</p>    
                
                <div class="container">
                    {% if user_file_present %}
                        <button id="button" onclick="showhide()">Show user files</button>
                        
                        
                        <div class="container" id="toggalable" style="display:none;">
                        <p>Proof of Identity</p>
                        <embed src="{{user_files.proof_of_identity.url}}" width="1000" height="375" type="application/pdf">
                        
                        
                        <br>
                        <br>
                        
                        
                        <p>Proof of Address</p>
                        <embed src="{{user_files.proof_of_address.url}}" width="1000" height="375" type="application/pdf">
                        
                        
                        <br>
                        <br>
                        
                        
                        <p>Proof of GSTIN</p>
                        <embed src="{{user_files.proof_of_gst.url}}" width="1000" height="375" type="application/pdf">
                        </div>
                        <br>
                        <br>
        
                    {% endif %}
                </div>

                    <form style="display: inline;" action="{% url 'administration:user_action' pk=userinfo.id %}" method=POST>
                        {% csrf_token %}
                        {% if userinfo.admin_approved %}
                            <button id="approve-btn" name="remove" type="submit">Withdraw Approval</button>
                        {% elif userinfo.documents_uploaded %}
                            <button id="approve-btn" name="approve" type="submit">Approve</button>
                            <button id="approve-btn" name="reject" type="submit">Reject documents</button>
                        {% else %}
                            <button id="approve-btn" name="notify" type="submit">Send reminder</button>
                            <button id="approve-btn" name="delete" type="submit">Delete User</button>
                        {% endif %}
                    </form>
                
    </div>
 {% endblock %}

solar_auction/administration/templates/administration/users.html
{% extends 'registration/base.html' %}
{% load static %}
{% block title %}
   {{page_title}}
{% endblock %}

{% block content %} 
    <div class="admin-content"> 
        {% if UserInfos %}
            <table class="table table-hover table-striped" id="sortable">
                <thead>
                    <tr>
                        
                        <th scope="col" onclick="sortTable(0)">Username</th>
                        <th scope="col" onclick="sortTable(1)">Email</th>
                        <th scope="col" onclick="sortTable(2)">Organization</th>
                        <th scope="col" onclick="sortTable(3)">Phone</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user_info in UserInfos %}
                        <tr>
                            
                            <td><a href="{% url 'administration:user_detail' user_info.id %}">{{user_info}}</a></td>
                            <td>{{user_info.user.email}}</td>
                            <td>{{user_info.organization_name}}</td>
                            <td>{{user_info.phone}}</td>
                        </tr> 
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>



 {% endblock %}