solar_auction/marketplace/urls.py
from django.urls import path
from . import views

app_name = 'marketplace'

urlpatterns = [
    path('', views.CatalogueListView.as_view(), name='all_catalogue'),
    path('marketplace_history', views.AuctionOverView.as_view(),
         name='history_catalogue'),
    path('detail/<slug:slug>/', views.CatalogueDetailView.as_view(),
         name='catalogue_detail'),
    path('user/catalogues/', views.UserCatalogueView.as_view(),
         name='user_catalogue'),
     path('bid_detail/<pk>/', views.BidDetailView.as_view(),
         name='bid_detail'),
    path('user/bids/', views.UserBidView.as_view(), name='user_bids'),
    path('user/add_item', views.addItemView, name='add_item'),
    path('<slug>/add_bid/', views.addBidView, name='add_bid'),
    path('notify/<slug>', views.notify_winner, name='notify_winner'),
    path('search', views.SearchView.as_view(), name='search')
]

solar_auction/payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    path('<slug>', views.home, name='payments_home'),
    path("payment/<slug>", views.order_payment, name="payment"),
    path('callback/', views.callback, name='payment_callback'),
    path('user_orders/', views.UserOrderView.as_view(), name='user_orders'),
]

solar_auction/solar_auction/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.i18n import JavaScriptCatalog
from django.contrib.auth import views as auth_views
from registration import views as registration_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jsi18n', JavaScriptCatalog.as_view(), name='js_catalog'),
    path('logout', registration_views.user_logout, name='logout'),
    path('', include('registration.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('dashboards/', include('administration.urls')),
    path('password-reset/', registration_views.ResetPasswordView.as_view(),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('payments/', include('payments.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

solar_auction/marketplace/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.template.defaultfilters import slugify
import random
from django.utils import timezone
from auditlog.registry import auditlog


class Catalogue(models.Model):
    name = models.CharField(max_length=256)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    details = models.CharField(max_length=1024)
    end_date = models.DateTimeField()
    starting_bid = models.PositiveIntegerField(default=0)
    admin_approved = models.BooleanField(default=False)
    slug = models.SlugField(unique=True, db_index=True)
    strategy_choices = (("ascending", 'low to high'),
                        ("descending", 'high to low'), ("quotes", 'get quotation'))
    strategy = models.CharField(max_length=10, choices=strategy_choices)
    broker_fees = models.FloatField(default=0)
    tech_specs = models.JSONField(blank=True, null=True)

    def auction_status(self):
        now = timezone.now()

        return now < self.end_date

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("catalogue_detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            slug_str = self.name + str(random.randint(1, 256))
            self.slug = slugify(slug_str)
        return super().save(*args, **kwargs)


class Bid(models.Model):
    catalogue_name = models.ForeignKey(Catalogue, on_delete=models.CASCADE)
    bid_amount = models.PositiveIntegerField()
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    
    tech_specs = models.JSONField(null=True, blank=True)

    def __str__(self):
        return 'Bid amount '+str(self.bid_amount) + ' on ' + self.catalogue_name.name

    

class CatalogueFile(models.Model):
    catalogue_name = models.ForeignKey(Catalogue, on_delete=models.CASCADE)
    file_name = models.FileField(
        upload_to="catalogue_file", blank=True, null=True)


auditlog.register(Catalogue)
auditlog.register(Bid)

solar_auction/marketplace/forms.py
from django import forms
from . import models
from django.contrib.admin.widgets import AdminSplitDateTime


class CatalogueForm(forms.Form):
    name = forms.CharField(max_length=256, label='Name your catalogue ')
    details = forms.CharField(max_length=1024, label='Additional Details ')
    end_date = forms.SplitDateTimeField(
        label='End auction on ', widget=AdminSplitDateTime())
    starting_bid = forms.IntegerField(
        label='Start bidding from ', required=False)
    strategy_choices = (("ascending", 'low to high'),
                        ("descending", 'high to low'), ("quotes", 'get quotation'))
    strategy = forms.ChoiceField(
        choices=strategy_choices, widget=forms.Select())


class BidForm(forms.ModelForm):
    bid_amount = forms.IntegerField(label='New Bid Amount')

    class Meta:
        model = models.Bid
        fields = ('bid_amount',)
        labels = {
            'bid_amount': 'New Bid Amount'
        }


class CatalogueFileForm(forms.ModelForm):
    file_name = forms.FileField(
        label='Additional Details', required=False)

    class Meta:
        model = models.CatalogueFile
        fields = ('file_name',)

solar_auction/marketplace/views.py
from .forms import CatalogueForm, BidForm, CatalogueFileForm
from .models import Catalogue, Bid, CatalogueFile
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseRedirect
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models import Max
from solar_auction.settings import EMAIL_HOST_USER
from django.core.mail import send_mail
from registration.models import UserProfileInfo
from django.utils import timezone
from django.views.decorators.clickjacking import xframe_options_exempt
from payments.models import Order
from payments.constants import PaymentStatus
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# Create your views here.
@method_decorator(login_required, name='dispatch')
class CatalogueListView(ListView):
    model = Catalogue
    context_object_name = 'catalogues'
    template_name = 'marketplace/catalogue_list.html'
    paginate_by = 5
    ordering = ['end_date']

    def get_queryset(self):
        if self.request.GET.get('ordering'):
            ordering = self.request.GET.get('ordering')
        else:
            ordering = 'end_date'

        query_set = Catalogue.objects.filter(
            admin_approved=True, end_date__gt=timezone.now()).order_by(ordering)
        return query_set

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = UserProfileInfo.objects.get(user=self.request.user)
        context['user_profile'] = current_user
        if self.request.GET.get('paginate_by'):
            context['paginate_by'] = self.request.GET.get('paginate_by')
        else:
            context['paginate_by'] = self.paginate_by

        if self.request.GET.get('ordering'):
            context['ordering'] = self.request.GET.get('ordering')
        else:
            context['ordering'] = self.ordering

        return context

    def get_paginate_by(self, queryset):

        return self.request.GET.get('paginate_by', self.paginate_by)


@method_decorator(login_required, name='dispatch')
class AuctionOverView(ListView):
    model = Catalogue
    context_object_name = 'catalogues'
    template_name = 'marketplace/catalogue_list.html'
    paginate_by = 5

    def get_queryset(self):
        return Catalogue.objects.filter(admin_approved=True, end_date__lt=timezone.now()).order_by('end_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = UserProfileInfo.objects.get(user=self.request.user)
        context['user_profile'] = current_user
        if self.request.GET.get('paginate_by'):
            context['paginate_by'] = self.request.GET.get('paginate_by')
        else:
            context['paginate_by'] = self.paginate_by
        return context

    def get_paginate_by(self, queryset):

        return self.request.GET.get('paginate_by', self.paginate_by)


@method_decorator(login_required, name='dispatch')
@method_decorator(xframe_options_exempt, name='dispatch')
class CatalogueDetailView(DetailView):
    model = Catalogue
    template_name = 'marketplace/catalogue_detail_new.html'
    context_object_name = 'catalogue'

    def get_context_data(self, **kwargs):
        context = super(CatalogueDetailView, self).get_context_data(**kwargs)
        current_user = UserProfileInfo.objects.get(user=self.request.user)
        context['user_profile'] = current_user
        all_bids = Bid.objects.filter(catalogue_name=context['catalogue'])

        # Get the overall highest bid/quote on this catalogue
        high_bid_on_catalogue = all_bids.order_by('bid_amount').first()
        if high_bid_on_catalogue:
            max_bid = high_bid_on_catalogue.bid_amount
        else:
            if context['catalogue'].strategy != 'quotes':
                max_bid = 'No bids yet'
            else:
                max_bid = 'No quotes yet'
        # Get the current users current bid/quote on this catalogue
        user_bids_on_catalogue = all_bids.filter(
            bidder=self.request.user).first()
        if user_bids_on_catalogue:
            current_user_high = user_bids_on_catalogue.bid_amount
        else:
            if context['catalogue'].strategy != 'quotes':
                current_user_high = "You haven't placed any bids on this yet."
            else:
                current_user_high = "You haven't quoted a price on this yet."

        context['max_bid'] = max_bid
        context['current_user_high'] = current_user_high
        # Get the catalogue detail file
        try:
            catalogue_file = CatalogueFile.objects.get(
                catalogue_name=context['catalogue'])
            context['file_present'] = True
            context['catalogue_file'] = catalogue_file
        except:
            context['file_present'] = False
        #  Find out if the current user has paid the token fee
        try:
            broker_payment = Order.objects.get(
                owner=current_user, catalogue=context['catalogue'], payment_status=PaymentStatus.SUCCESS)
            context['payment'] = True
            context['order_detail'] = broker_payment
        except:
            context['payment'] = False
        return context


@method_decorator(login_required, name='dispatch')
class UserCatalogueView(LoginRequiredMixin, ListView):

    context_object_name = 'catalogues'
    template_name = 'marketplace/user_catalogue.html'
    paginate_by = 5

    def get_queryset(self):
        try:
            return Catalogue.objects.filter(owner=self.request.user)
        except:
            raise Http404()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = UserProfileInfo.objects.get(user=self.request.user)
        context['user_profile'] = current_user
        if self.request.GET.get('paginate_by'):
            context['paginate_by'] = self.request.GET.get('paginate_by')
        else:
            context['paginate_by'] = self.paginate_by
        return context

    def get_paginate_by(self, queryset):

        return self.request.GET.get('paginate_by', self.paginate_by)


@method_decorator(login_required, name='dispatch')
class UserBidView(LoginRequiredMixin, ListView):

    context_object_name = 'bids'
    template_name = 'marketplace/user_bids.html'
    paginate_by = 5

    def get_queryset(self):
        try:
            return Bid.objects.filter(bidder=self.request.user)
        except:
            raise Http404()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = UserProfileInfo.objects.get(user=self.request.user)
        context['user_profile'] = current_user
        if self.request.GET.get('paginate_by'):
            context['paginate_by'] = self.request.GET.get('paginate_by')
        else:
            context['paginate_by'] = self.paginate_by
        return context

    def get_paginate_by(self, queryset):

        return self.request.GET.get('paginate_by', self.paginate_by)


@login_required
def addItemView(request):
    error_list = []
    if request.FILES:
        file_form = CatalogueFileForm(request.POST, request.FILES)
    else:
        file_form = CatalogueFileForm()

    if request.method == 'POST':
        form = CatalogueForm(request.POST)
        specifications = request.POST.getlist('field_name[]')
        specification_values = request.POST.getlist('selected_ids[]')
        if len(specifications) != len(specification_values):
            error_list.append(
                'Please choose only one parameter for technical specifications.')
        if form.is_valid() and len(specifications) == len(specification_values):
            technical_specifications = {}
            print(request.POST)

            for n in range(len(specifications)):
                technical_specifications[specifications[n]
                                         ] = specification_values[n]

            new_catalogue = Catalogue(name=form.cleaned_data['name'],
                                      owner=request.user,
                                      details=form.cleaned_data['details'],

                                      end_date=form.cleaned_data['end_date'],
                                      starting_bid=form.cleaned_data['starting_bid'], strategy=form.cleaned_data[
                                          'strategy'], tech_specs=technical_specifications,

                                      )
            new_catalogue.save()
            if request.FILES:
                catalogue_file = CatalogueFile(
                    catalogue_name=new_catalogue, file_name=request.FILES['file_name'])
                catalogue_file.save()
            return HttpResponseRedirect(reverse('marketplace:user_catalogue'))

    else:
        form = CatalogueForm()
        file_form = CatalogueFileForm()
    user_profile = UserProfileInfo.objects.get(user=request.user)
    return render(request, 'marketplace/add_item.html', {'form': form, 'user': request.user, 'user_profile': user_profile, 'file_form': file_form, 'error_list': error_list})


@login_required
def addBidView(request, slug):
    catalogue = Catalogue.objects.get(slug=slug)
    strategy = catalogue.strategy
    current_user = UserProfileInfo.objects.get(user=request.user)
    users_bid = Bid.objects.filter(
        catalogue_name=catalogue, bidder=request.user)
    if len(users_bid) == 0:
        user_bid_status = 'No bid'
        if strategy == 'quotes':
            current_value = 0
        else:
            current_value = catalogue.starting_bid
    else:
        current_value = users_bid[0].bid_amount
        user_bid_status = 'Bid'
    print(current_value)

solar_auction/marketplace/templates/marketplace/catalogue_detail.html
{% extends 'registration/base.html' %}
{% load static %}

{% block title %}
  Catalogue Detail
{% endblock %}

{% block content %}
{% if catalogue.admin_approved or catalogue.owner == user %}
        <div class="container">
                <h1>Name: {{catalogue.name}}</h1>
                <p>Details: {{catalogue.details}}</p>
                {% if catalogue.starting_bid  %}<p>Base price: {{ catalogue.starting_bid }}</p>{% endif %}
                <p>End date: {{catalogue.end_date}}</p>
                <p>Bidding Strategy: {% if catalogue.strategy == 'ascending' %}Low to High{% elif catalogue.strategy == 'descending' %}High to Low{% else %}Get Quotations{% endif %}</p>
                <p>{% if catalogue.auction_status %} 
                    On Auction 
                  {% else %} 
                    Auction over
                        {% if catalogue.owner == user %}
                          <p> Winner is : {{max_bidder}} </p>
                          <form class="small-form" action="{% url 'marketplace:notify_winner' catalogue.slug %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" name="">Notify Winner</button>
                          </form>
                        {% endif %}
                  {% endif %}
                </p>
          </div>
          {% if file_present %}
          
          <div class="container" id="toggleable">
                
                
                <embed src="{{catalogue_file.file_name.url}}" width="1000" height="375" type="application/pdf">
                  
                
          </div>
          {% endif %}
    {% if catalogue.strategy == 'quotes' %}
          <div class="container">
                {% if catalogue.owner != user %}
                  <p>Your quote : {{current_user_high}}</p>
                {% else %}
                <p>Do something when the owner wants to see the quotes</p>
                {% endif %}
          </div>
    {% else %}
        <div class="container">
          <h2> 
            {% if catalogue.auction_status %} 
                Current Winning Bid: {{max_bid}}
            {% else %}
              Winning Bid: {{max_bid}} 
            {% endif %}
          </h2>
        </div>
    {% endif %}
  
    {% if catalogue.owner != user%}
          <div class="container">
            {% if catalogue.strategy != 'quotes' %}
            <p>Your bid : {{current_user_high}}</p>
            {% endif %}
            {% if catalogue.auction_status and catalogue.admin_approved %}
                <form action="{% url 'marketplace:add_bid' catalogue.slug %}" method="GET">
                {% csrf_token %}
                <input type="checkbox" required="True">I agree to the website's Terms and conditions.</input>
                <br>
                <input type="checkbox" required="True">I have read and understand the customer's requirements and i'm ready to fulfil them.</input>
                <br>
                <br>
                <a href="{% url 'payments:payments_home' catalogue.slug%}">Pay the token fee</a>
                <button type="submit" name="">Bid on this item</button>
              </form>
            {% endif %}
          </div>
    {% endif %}
{% endif %}


{% if not catalogue.admin_approved %}
    <div class="container">
      <p> Waiting admin approval </p>
    </div>  
  
{% endif %}

<script type="text/javascript" language="JavaScript">
mydiv = document.getElementById("toggleable");

function showhide(d) {
    d.style.display = (d.style.display !== "none") ? "none" : "block";
}
</script>




{% endblock %}

solar_auction/marketplace/templates/marketplace/catalogue_detail_new.html
{% extends 'registration/base.html' %}
{% load static %}

{% block title %}
  Catalogue Detail
{% endblock %}

{% block content %}
    {% if catalogue.admin_approved or catalogue.owner == user %}
    <!-- Show the catalogue details here if it is approved or it is owned by the viewer -->
        <h1>Name: {{catalogue.name}}</h1>
        <p>Details: {{catalogue.details}}</p>
        {% if catalogue.starting_bid  %}
            <p>Base price: {{ catalogue.starting_bid }}</p>
        {% endif %}
        <p>End date: {{catalogue.end_date}}</p>
        <p>Bidding Strategy: 
            {% if catalogue.strategy == 'ascending' %}
                Low to High
            {% elif catalogue.strategy == 'descending' %}
                High to Low
            {% else %}
                Get Quotations
            {% endif %}
        </p>
        {% if catalogue.tech_specs %}
            <p>Technical specifications</p> 
            
            <ol>
                {% for key,value in catalogue.tech_specs.items %}
                    <li>
                        {{key}} ({{value}})  
                    </li>
                {% endfor %}
            </ol>
        {% endif %}
        <p>{% if catalogue.auction_status %}On Auction{% else %}Auction over{% endif %}</p>
        {% if file_present %}
            <button id="button" onclick="showhide()">Additional customer requirements</button>
            <br>
            <br>
            <div class="container" id="toggalable" style="display:none;">
                <embed src="{{catalogue_file.file_name.url}}" width="1000" height="375" type="application/pdf">
            </div>
        {% endif %}
        
    {% endif %}


    {% if catalogue.admin_approved %}
    <!-- If catalogue is approved  -->
        {% if catalogue.owner == user %}
        <!-- If the viewer is owner -->
            {% if catalogue.auction_status %}
            <!-- If the auction is still ongoing -->
                {% if catalogue.strategy == 'quotes' %}
                <!-- Show the owner all the quotes here -->
                {% else %}
                <!-- Show the owner highest bids here -->
                    Current Winning Bid: {{max_bid}}
                {% endif %}
            {% else %}
            <!-- If the auction is over -->
                {% if catalogue.strategy == 'quotes' %}
                <!-- Show the owner all the quotes here -->
                <!-- Allow the owner to contact the desired person-->  
                {% else %}
                <!-- Show the owner highest bids here -->
                <!-- Allow the owner to contact the highest bidder-->  
                {% endif %}
            {% endif %}
        {% else %}
        <!-- If the viewer is a bidder -->
            {% if catalogue.auction_status %}
            <!-- Allow the bidders to see the highest bids,their highestbid and allow them to bid -->
                <h2>Current Winning Bid: {{max_bid}}</h2>
                
                
                {% if catalogue.broker_fees and not payment %}
                <!-- If there is a token fee and customer has not paid then make them pay -->
                    <a class="payment-button" href="{% url 'payments:payments_home' catalogue.slug%}">Pay token fee</a>
                {% else %}
                <!-- If there is no token fee or token fee already paid then allow the bidders to bid -->
                    <p>Your bid : {{current_user_high}}</p>
                    <form action="{% url 'marketplace:add_bid' catalogue.slug %}" method="GET">
                        {% csrf_token %}
                        <input type="checkbox" required="True">I agree to the website's Terms and conditions.</input>
                        <br>
                        <input type="checkbox" required="True">I have read and understand the customer's requirements and i'm ready to fulfil them.</input>
                        <br>
                        <br>
                        <button type="submit" name="">Bid on this item</button>
                    </form>
                {% endif %}
            {% else %}
            <!-- Allow the bidders to see the winning bid -->
            {% endif %}
        {% endif %}
    {% else %}
    <!-- If catalogue is not approved show appropriate message  -->
        <p>Awaiting admin approval</p>
    {% endif %}
    

{% endblock %}

solar_auction/marketplace/templates/marketplace/user_bids.html
{% extends 'registration/base.html' %}
{% load static %}

{% block title %}
  Your Bids
{% endblock %}

{% block content %}
<div class="container">
  {% comment %} <div class="jumbotron"> {% endcomment %}
        {% if bids %}
      <table class="table table-hover table-striped" id="sortable">
                    <thead>
                        <tr>
                        
                        <th scope="col" onclick="sortTable(0)" >Name</th>
                        <th scope="col" onclick="sortTable(1)">Bid Amount</th>
                        <th scope="col" onclick="sortTable(2)">Closing Date</th>
                        
                        
                        </tr>
                    </thead>
                    <tbody>
                        {% for bid in bids %}
                        <tr>
                            
                            <td><a href="{% url 'marketplace:catalogue_detail' bid.catalogue_name.slug %}">{{bid.catalogue_name.name}}</a></td>
                            <td><a href="{% url 'marketplace:bid_detail' bid.pk %}">{{bid.bid_amount}}</a></td>
                            <td>{{bid.catalogue_name.end_date}}</td>
                            
                            
                        </tr> 
                        {% endfor %}
                    </tbody>
                </table>
        {% else %}
        <div class="container">
        <p>You have not placed any bids on any items. Go to <a href="{% url 'marketplace:all_catalogue' %}">MarketPlace</a> to bid on an item.</p>
        </div>
        {% endif %}
      
  {% comment %} </div> {% endcomment %}
</div>
<div class="container">
{% if is_paginated %}
        <div class="pagination">
            
                {% if page_obj.has_previous %}
                    <a href="?paginate_by={{ paginate_by }}&page=1"> &laquo First &nbsp </a>
                    <a href="?paginate_by={{ paginate_by }}&page={{ page_obj.previous_page_number }}"> previous &nbsp </a>
                {% endif %}
                
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                
                {% if page_obj.has_next %}
                    <a href="?paginate_by={{ paginate_by }}&page={{ page_obj.next_page_number }}"> &nbsp next &nbsp </a>
                    <a href="?paginate_by={{ paginate_by }}&page={{ page_obj.paginator.num_pages }}"> Last &raquo  </a>
                {% endif %}
            
        </div>
    {% endif %} 
    <br>
    
<form action="" method="get">
    Show 
    <select name="paginate_by">
        <option {% if paginate_by == '2' %}selected{% endif %}>2</option>
        <option {% if paginate_by == '3' %}selected{% endif %}>3</option>
        <option {% if paginate_by == '5' or paginate_by == 5 %}selected{% endif %}>5</option>
        <option {% if paginate_by == '10' %}selected{% endif %}>10</option>
    </select>
    <input type="submit" value="Results/page">
</form>
</div>
{% endblock %}

solar_auction/marketplace/templates/marketplace/user_catalogue.html
{% extends 'registration/base.html' %}
{% load static %}

{% block title %}
  Your Catalogue
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'marketplace/styles.css' %}">
{% endblock %}
{% block content %}

    
    
    <div class="container">
        
        
    {% comment %} <div class="jumbotron"> {% endcomment %}
        <form class="form-inline my-2 my-lg-0 search-form inline-form"  action="{% url 'marketplace:search' %}" method="GET">
            
            <input class="form-control mr-sm-2 search-box" type="search" placeholder="Search Marketplace" aria-label="Search" name="search" >
          
        </form>
        {% if user_profile.admin_approved %}
            <form class="small-form inline-form add-item-form" action="{% url 'marketplace:add_item' %}" enctype="multipart/form-data" method="GET">
                {% csrf_token %}
                <button type="submit" name="">Add a new item</button>
            </form>
        {% endif %}
        <br>
        <br>
    
        {% if user_profile.admin_approved %}
            
            {% comment %} <h2><li><a href="{% url 'marketplace:catalogue_detail' catalogue.slug %}">{{catalogue.name}}</a></li></h2> {% endcomment %}
                {% if catalogues %}
                <table class="table table-hover table-striped" id="sortable">
                    <thead>
                        <tr>
                        
                        <th scope="col" onclick="sortTable(0)">Name</th>
                        <th scope="col" onclick="sortTable(1)">End date</th>
                        <th scope="col" onclick="sortTable(2)">Starting Bid Amount</th>
                        <th scope="col" onclick="sortTable(3)">Admin Approved</th>
                        <th scope="col" onclick="sortTable(4)">Auction Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for catalogue in catalogues %}
                        <tr>
                            
                            <td><a href="{% url 'marketplace:catalogue_detail' catalogue.slug %}">{{catalogue.name}}</a></td>
                            <td>{{catalogue.end_date}}</td>
                            <td>{{catalogue.starting_bid}}</td>
                            <td>{% if catalogue.admin_approved %}Yes{% else %}No{% endif %}</td>
                            <td>{% if catalogue.auction_status %}On Auction{% else %}Auction Over{% endif %}</td>
                        </tr>
                        {% endfor %} 
                    </tbody>
                </table>
                {% else %}
                <div class="container">
                <p>You do not own any catalogues.</p>
                </div>
                {% endif %}
        {% else %}
            <h2>Please verify your email first by submitting the documents.</h2>
        {% endif %}
    {% comment %} </div> {% endcomment %}
    </div>
<div class="container">
{% if is_paginated %}
        <div class="pagination">
            
                {% if page_obj.has_previous %}
                    <a href="?paginate_by={{ paginate_by }}&page=1"> &laquo First &nbsp </a>
                    <a href="?paginate_by={{ paginate_by }}&page={{ page_obj.previous_page_number }}"> previous &nbsp </a>
                {% endif %}
                
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                
                {% if page_obj.has_next %}
                    <a href="?paginate_by={{ paginate_by }}&page={{ page_obj.next_page_number }}"> &nbsp next &nbsp </a>
                    <a href="?paginate_by={{ paginate_by }}&page={{ page_obj.paginator.num_pages }}"> Last &raquo  </a>
                {% endif %}
            
        </div>
    {% endif %} 
    <br>
    
<form action="" method="get">
    Show 
    <select name="paginate_by">
        <option {% if paginate_by == '2' %}selected{% endif %}>2</option>
        <option {% if paginate_by == '3' %}selected{% endif %}>3</option>
        <option {% if paginate_by == '5' or paginate_by == 5 %}selected{% endif %}>5</option>
        <option {% if paginate_by == '10' %}selected{% endif %}>10</option>
    </select>
    <input type="submit" value="Results/page">
</form>
</div>
{% endblock %}