solar_auction/marketplace/urls.py
from django.urls import path
from . import views

app_name = 'marketplace'

urlpatterns = [
    path('', views.CatalogueListView.as_view(), name='all_catalogue'),
    path('marketplace_history', views.AuctionOverView.as_view(),
         name='history_catalogue'),
    path('detail/<slug:slug>/', views.CatalogueDetailView.as_view(),
         name='catalogue_detail'),
    path('user/catalogues/', views.UserCatalogueView.as_view(),
         name='user_catalogue'),
     path('bid_detail/<pk>/', views.BidDetailView.as_view(),
         name='bid_detail'),
    path('user/bids/', views.UserBidView.as_view(), name='user_bids'),
    path('user/add_item', views.addItemView, name='add_item'),
    path('<slug>/add_bid/', views.addBidView, name='add_bid'),
    path('notify/<slug>', views.notify_winner, name='notify_winner'),
    path('search', views.SearchView.as_view(), name='search')
]

solar_auction/payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    path('<slug>', views.home, name='payments_home'),
    path("payment/<slug>", views.order_payment, name="payment"),
    path('callback/', views.callback, name='payment_callback'),
    path('user_orders/', views.UserOrderView.as_view(), name='user_orders'),
]

solar_auction/solar_auction/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.i18n import JavaScriptCatalog
from django.contrib.auth import views as auth_views
from registration import views as registration_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jsi18n', JavaScriptCatalog.as_view(), name='js_catalog'),
    path('logout', registration_views.user_logout, name='logout'),
    path('', include('registration.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('dashboards/', include('administration.urls')),
    path('password-reset/', registration_views.ResetPasswordView.as_view(),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('payments/', include('payments.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

solar_auction/payments/models.py
from django.db import models
from registration.models import UserProfileInfo
from marketplace.models import Catalogue
from auditlog.registry import auditlog
from .constants import PaymentStatus
# Create your models here.


class Order(models.Model):
    owner = models.ForeignKey(
        UserProfileInfo, on_delete=models.CASCADE, verbose_name="customer")
    catalogue = models.ForeignKey(Catalogue, on_delete=models.CASCADE)
    fee_amount = models.FloatField()
    payment_status = models.CharField(
        default=PaymentStatus.PENDING, max_length=100, blank=False, null=False,)
    order_id = models.CharField(max_length=100)
    payment_id = models.CharField(max_length=100)
    signature_id = models.CharField(max_length=100)

    def __str__(self):
        return str(self.owner) + ' on ' + str(self.catalogue) + ' ' + str(self.payment_status)


auditlog.register(Order)

solar_auction/payments/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from registration.models import UserProfileInfo
from solar_auction.settings import RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET
from marketplace.models import Catalogue
from django.contrib.sites.shortcuts import get_current_site
import razorpay
from .models import Order
from django.views.decorators.csrf import csrf_exempt
import json
from .constants import PaymentStatus
from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required
def home(request, slug):
    try:
        user_profile = UserProfileInfo.objects.get(pk=request.user.id)
    except:
        user_profile = {}

    context_dict = {'user_profile': user_profile}
    try:
        current_catalogue = Catalogue.objects.get(slug=slug)
    except:
        current_catalogue = {}
    context_dict['catalogue'] = current_catalogue
    return render(request, "payments/index.html", context_dict)


def order_payment(request, slug):
    try:
        user_profile = UserProfileInfo.objects.get(pk=request.user.id)
    except:
        user_profile = {}

    context_dict = {'user_profile': user_profile}

    # Get the User details, Catalogue Details and the token fees
    current_user = user_profile
    current_catalogue = Catalogue.objects.get(slug=slug)

    amount = current_catalogue.broker_fees
    current_site = str(get_current_site(request))

    if request.method == 'POST':
        client = razorpay.Client(auth=(RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET))
        razorpay_order = client.order.create({"amount": int(amount) * 100, "currency": "INR",
                                              "payment_capture": "1"})
        order = Order.objects.create(
            owner=current_user, catalogue=current_catalogue, fee_amount=amount, order_id=razorpay_order[
                "id"]
        )
        order.save()
        context_dict['amount'] = amount
        context_dict['razorpay_key'] = RAZORPAY_KEY_ID
        context_dict['order'] = order
        context_dict['catalogue'] = current_catalogue
        context_dict['callback_url'] = "http://" + \
            current_site + "/payments/callback/"
    return render(request, 'payments/payment.html', context_dict)


@csrf_exempt
def callback(request):
    try:
        user_profile = UserProfileInfo.objects.get(pk=request.user.id)
    except:
        user_profile = {}

    context_dict = {'user_profile': user_profile}

    def verify_signature(response_data):
        client = razorpay.Client(auth=(RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET))
        return client.utility.verify_payment_signature(response_data)

    if "razorpay_signature" in request.POST:

        payment_id = request.POST.get("razorpay_payment_id", "")
        order_id = request.POST.get("razorpay_order_id", "")
        signature_id = request.POST.get("razorpay_signature", "")
        order = Order.objects.get(order_id=order_id)
        order.payment_id = payment_id
        order.signature_id = signature_id
        order.save()
        context_dict['catalogue'] = Catalogue.objects.get(
            slug=order.catalogue.slug)
        if verify_signature(request.POST):
            order.payment_status = PaymentStatus.SUCCESS
            order.save()
            context_dict['status'] = order.payment_status
            return render(request, "payments/callback.html", context_dict)
        else:
            order.payment_status = PaymentStatus.FAILURE
            order.save()
            context_dict['status'] = order.payment_status
            return render(request, "payments/callback.html", context_dict)
    else:
        payment_id = json.loads(request.POST.get(
            "error[metadata]")).get("payment_id")
        order_id = json.loads(request.POST.get("error[metadata]")).get(
            "order_id"
        )
        order = Order.objects.get(order_id=order_id)
        order.payment_id = payment_id
        order.payment_status = PaymentStatus.FAILURE
        order.save()
        context_dict['status'] = order.payment_status
        return render(request, "payments/callback.html", context_dict)


@method_decorator(login_required, name='dispatch')
class UserOrderView(ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'payments/user_order_list.html'

    def get_queryset(self):
        current_user = UserProfileInfo.objects.get(user=self.request.user)
        user_orders = Order.objects.filter(
            owner=current_user, payment_status=PaymentStatus.SUCCESS)
        return user_orders

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = UserProfileInfo.objects.get(user=self.request.user)
        context['user_profile'] = current_user
        return context

solar_auction/payments/templates/payments/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    
  </body>
</html>

solar_auction/payments/templates/payments/callback.html
{% extends 'registration/base.html' %}
{% block content %}
<div class="text-center" style="margin-top:20%">
    {% if status == "Success" %}
    <h2>THANKS YOUR PAYMENT HAS BEEN RECEIVED</h2>
    <a href="{% url 'marketplace:catalogue_detail' catalogue.slug %}">Go back</a>
    {% else %}
    <h2>SORRY, YOUR PAYMENT HAS FAILED</h2>
    
    {% endif %}
    <a href="{% url 'marketplace:all_catalogue' %}">Go back</a>
</div>
{% endblock %}

solar_auction/payments/templates/payments/index.html
{% extends 'registration/base.html' %}
{% block title %}
    Proceed to Payment
{% endblock %}
{% block content %}
<form action="{% url 'payments:payment' catalogue.slug %}" method="POST">
        {% csrf_token %}
        <p>The brokerage amount will be : {{catalogue.broker_fees}} INR.</p>
        <p>You will be redirected to Razorpay payments page.</p>
        <a class="reject-button" style="display:inline" href="{% url 'marketplace:catalogue_detail' catalogue.slug %}">No, Go back</a>
        <button style="display:inline" type="submit">Pay</button>
        
        
    </form>
{% endblock %}

solar_auction/payments/templates/payments/payment.html
{% extends 'registration/base.html' %}
{% block title %}
    Proceed to Payment
{% endblock %}
{% load static %}
{% block content %}
        <a href="{% url 'marketplace:catalogue_detail' catalogue.slug %}">back</a>
    
        <form method="POST">
            <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
            <script>
            var options = {
                key: "{{razorpay_key}}",
                amount: "{{amount}}", 
                currency: "INR",
                name: "{{catalogue.name}}",
                description: "Token fee",
                image: "{% static 'images/logo.png'%}",
                order_id: "{{order.order_id}}",
                callback_url: "{{callback_url}}",
                redirect: true,
                prefill: {
                    "name": "{{user_profile.name}}",
                    "email": "{{user_profile.user.email}}",
                    "contact": "{{user_profile.phone}}"
                 },
                notes: {
                    "address": "Razorpay Corporate Office"
                },
                theme: {
                    "color": "#4a154b"
                }
            };
            var rzp1 = new Razorpay(options);
            rzp1.open();
            </script>
            <input type="hidden" custom="Hidden Element" name="hidden">
        </form>
    
{% endblock %}

solar_auction/payments/templates/payments/user_order_list.html
{% extends 'registration/base.html' %}
{% block title %}
    My orders
{% endblock %}
{% block content %}
    {% if orders %}
        <table class="table table-hover table-striped" id="sortable">
            <thead>
                <tr>
                    <th scope="col" onclick="sortTable(0)">Catalogue Name</th>
                    <th scope="col" onclick="sortTable(1)">Amount</th>
                    <th scope="col" onclick="sortTable(2)">Payment Status</th>
                    <th scope="col" onclick="sortTable(3)">Order Id</th>
                    <th scope="col" onclick="sortTable(4)">Auction status</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                    <tr>
                        <td><a href="{% url 'marketplace:catalogue_detail' order.catalogue.slug %}">{{order.catalogue}}</a></td>
                        <td>{{order.fee_amount}}</td>
                        <td>{{order.payment_status}}</td>
                        <td>{{order.order_id}}</td>
                        <td>{% if order.catalogue.auction_status %}On Auction{% else %}Auction Over{% endif %}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}